dbt_fanareas:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: "{{ env_var('hostname') }}"
      port: 25060
      user: "{{ env_var('uid') }}"
      pass: "{{ env_var('pwd') }}"
      dbname: "{{ env_var('db') }}"
      schema: public

    prod:
      type: postgres
      threads: 1
      host: "{{ env_var('hostname') }}"
      port: 25060
      user: "{{ env_var('uid') }}"
      pass: "{{ env_var('pwd') }}"
      dbname: "{{ env_var('db') }}"
    schema: public

  target: dev